### ISSUE TITLE
Conda-forge doesn't seem to have updated to v0.0.5?

### ISSUE THREAD

**Issue by TomNicholas** [cubed-dev/cubed-xarray#12]
The [conda-forge page for cubed-xarray](https://anaconda.org/conda-forge/cubed-xarray) seems to be stuck on v0.0.4 instead of 0.0.5 and I'm not sure why

**Comment by jhamman** [comment]
https://github.com/conda-forge/cubed-xarray-feedstock/pull/2 ?

**Comment by TomNicholas** [comment]
Thank you @jhamman ! Nice to know someone else is watching this repo 😁
